In [1]:
import pandas as pd
#read in 538 SPI data (needs to scheduled after BPL matchday is completed)
teams = pd.read_csv("https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv")

Base_BPL=teams[(teams.league=='Barclays Premier League')|(teams.league=='English League Championship')]

In [2]:
Base_BPL

,rank,prev_rank,name,league,off,def,spi
0,1,1,Manchester City,Barclays Premier League,2.79,0.25,92.42
2,3,3,Chelsea,Barclays Premier League,2.42,0.20,90.53
4,5,5,Liverpool,Barclays Premier League,2.69,0.40,89.17
7,8,8,Manchester United,Barclays Premier League,2.41,0.46,85.53
12,13,13,Arsenal,Barclays Premier League,2.18,0.42,83.72
24,25,25,Brighton and Hove Albion,Barclays Premier League,1.97,0.51,78.71
25,26,26,Leicester City,Barclays Premier League,2.14,0.64,78.22
26,27,27,Tottenham Hotspur,Barclays Premier League,2.31,0.76,78.06
33,34,34,West Ham United,Barclays Premier League,2.18,0.76,76.00
35,36,36,Leeds United,Barclays Premier League,2.13,0.78,74.94
42,43,43,Everton,Barclays Premier League,1.86,0.70,72.28
43,44,44,Aston Villa,Barclays Premier League,2.02,0.82,72.18
57,58,57,Wolverhampton,Barclays Premier League,1.73,0.72,69.61
58,59,59,Fulham,Barclays Premier League,1.68,0.74,68.01
60,61,61,Newcastle,Barclays Premier League,1.93,0.94,67.79
64,65,65,Brentford,English League Championship,1.74,0.83,67.01
65,66,66,Southampton,Barclays Premier League,1.88,0.93,67.01
67,68,68,Burnley,Barclays Premier League,1.85,0.92,66.79
76,77,77,Norwich City,English League Championship,1.82,0.97,65.03
95,96,96,Crystal Palace,Barclays Premier League,1.69,1.00,61.55
110,111,109,West Bromwich Albion,Barclays Premier League,1.78,1.16,59.72
113,114,113,Watford,English League Championship,1.52,0.94,59.48
136,137,136,AFC Bournemouth,English League Championship,1.54,1.07,56.67
143,144,140,Sheffield United,Barclays Premier League,1.44,0.99,56.30
147,148,143,Barnsley,English League Championship,1.38,0.96,55.91
168,169,168,Blackburn,English League Championship,1.50,1.19,52.88
178,179,179,Cardiff City,English League Championship,1.46,1.22,51.41
184,185,184,Stoke City,English League Championship,1.25,1.03,50.95
187,188,189,Queens Park Rangers,English League Championship,1.51,1.31,50.33
207,208,210,Rotherham United,English League Championship,1.31,1.20,48.12
209,210,212,Reading,English League Championship,1.30,1.20,47.84
216,217,220,Swansea City,English League Championship,1.20,1.13,47.10
219,220,222,Preston North End,English League Championship,1.20,1.14,46.87
221,222,224,Middlesbrough,English League Championship,1.24,1.19,46.79
228,229,232,Coventry City,English League Championship,1.27,1.25,46.03
243,244,243,Derby County,English League Championship,1.17,1.19,44.85
246,247,246,Millwall,English League Championship,1.25,1.29,44.77
247,248,247,Luton Town,English League Championship,1.20,1.24,44.65
251,252,252,Nottingham Forest,English League Championship,1.07,1.11,44.18
263,264,265,Sheffield Wednesday,English League Championship,1.21,1.31,43.15
270,271,273,Wycombe Wanderers,English League Championship,1.22,1.35,42.59
285,286,286,Birmingham,English League Championship,1.10,1.25,41.68
349,350,351,Huddersfield Town,English League Championship,1.10,1.45,37.52
449,450,450,Bristol City,English League Championship,1.02,1.72,30.18

In [3]:
#configure names to fit with understat csv names
Name=Base_BPL["name"]
Name.replace('\s+', '_',regex=True,inplace=True)
t1=Name.replace('Brighton_and_Hove_Albion','Brighton')
t2=t1.replace('Leeds_United','Leeds')
t3=t2.replace('Leicester_City','Leicester')
t4=t3.replace('Newcastle','Newcastle_United')
t5=t4.replace('Norwich_City','Norwich')
t6=t5.replace('Tottenham_Hotspur','Tottenham')
t7=t6.replace('West_Ham_United','West_Ham')
t8=t7.replace('Wolverhampton','Wolverhampton_Wanderers')
t9=t8.replace('AFC_Bournemouth','Bournemouth')
t10=t9.sort_values()
t10

/Users/EddyZulkifly/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

12                     Arsenal
43                 Aston_Villa
147                   Barnsley
285                 Birmingham
168                  Blackburn
136                Bournemouth
64                   Brentford
24                    Brighton
449               Bristol_City
67                     Burnley
178               Cardiff_City
2                      Chelsea
228              Coventry_City
95              Crystal_Palace
243               Derby_County
42                     Everton
58                      Fulham
349          Huddersfield_Town
35                       Leeds
25                   Leicester
4                    Liverpool
247                 Luton_Town
0              Manchester_City
7            Manchester_United
221              Middlesbrough
246                   Millwall
60            Newcastle_United
76                     Norwich
251          Nottingham_Forest
219          Preston_North_End
187        Queens_Park_Rangers
209                    Reading
207           Rotherham_United
143           Sheffield_United
263        Sheffield_Wednesday
65                 Southampton
184                 Stoke_City
216               Swansea_City
26                   Tottenham
113                    Watford
110       West_Bromwich_Albion
33                    West_Ham
57     Wolverhampton_Wanderers
270          Wycombe_Wanderers
Name: name, dtype: object

In [4]:
#reading in data and merging files
#define understat which reads csv
understat = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2019-20/understat/understat_"+t10.iloc[5]+".csv")
#define merge which is the variable that stores all data
merge=understat.drop(understat.index)
#creates column for team
merge['team']=""
#need to add a loop, within each loop, add team name for identification
#merge into new dataframe, repeat till all data pulled from repo

In [5]:
#need to check if data is good or not status code 200 or nah
import requests
for i in t10:
    check=requests.get("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2019-20/understat/understat_"+str(i)+".csv")
    if check.status_code == 200:
        understat = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2019-20/understat/understat_"+str(i)+".csv")
        understat['team']=str(i)
        merge=merge.append(understat)
    else:
        continue

merge['Season']='19-20'
merge

,date,deep,deep_allowed,draws,h_a,loses,missed,npxG,npxGA,npxGD,...,ppda_allowed,pts,result,scored,wins,xG,xGA,xpts,team,Season
0,2019-08-11 14:00:00,10,1,0,a,0,0,1.133090,0.380551,0.752539,...,"{'att': 383, 'def': 29}",3,w,1,1,1.133090,0.380551,2.0730,Arsenal,19-20
1,2019-08-17 12:30:00,8,4,0,h,0,1,1.164400,1.391720,-0.227320,...,"{'att': 296, 'def': 26}",3,w,2,1,1.164400,1.391720,1.1533,Arsenal,19-20
2,2019-08-24 17:30:00,7,9,0,a,1,3,0.985542,2.027040,-1.041498,...,"{'att': 362, 'def': 37}",0,l,1,0,0.985542,2.788210,0.3434,Arsenal,19-20
3,2019-09-01 16:30:00,12,6,1,h,0,2,1.925090,1.193970,0.731120,...,"{'att': 207, 'def': 17}",1,d,2,0,1.925090,1.955140,1.2919,Arsenal,19-20
4,2019-09-15 15:30:00,7,12,1,a,0,2,1.006160,2.070920,-1.064760,...,"{'att': 254, 'def': 28}",1,d,2,0,1.006160,2.832090,0.3084,Arsenal,19-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,2020-07-08 17:00:00,2,7,0,a,1,1,0.326909,0.470483,-0.143574,...,"{'att': 340, 'def': 18}",0,l,0,0,0.326909,0.470483,1.0775,Wolverhampton_Wanderers,19-20
34,2020-07-12 11:00:00,4,3,0,h,0,0,2.106070,0.286561,1.819509,...,"{'att': 354, 'def': 19}",3,w,3,1,2.867240,0.286561,2.8945,Wolverhampton_Wanderers,19-20
35,2020-07-15 17:00:00,3,6,1,a,0,1,1.285700,0.773179,0.512521,...,"{'att': 201, 'def': 26}",1,d,1,0,1.285700,1.534350,1.0986,Wolverhampton_Wanderers,19-20
36,2020-07-20 19:15:00,4,1,0,h,0,0,1.486960,0.440119,1.046841,...,"{'att': 257, 'def': 22}",3,w,2,1,1.486960,0.440119,2.3593,Wolverhampton_Wanderers,19-20
37,2020-07-26 15:00:00,2,7,0,a,1,2,0.164561,1.159380,-0.994819,...,"{'att': 198, 'def': 29}",0,l,0,0,0.164561,1.159380,0.4276,Wolverhampton_Wanderers,19-20

In [6]:
merge.to_csv('2019-2020_Team_Understat.csv')